### ISSUE TITLE
[BUG]Graphical glitch with Super Mario 64 stars.

### ISSUE THREAD

**Issue by Deadfalt999** [masterfeizz/DaedalusX64-3DS#1]
Describe the bug
The stars in Mario 64 flickers between a greyish color and yellow.

To Reproduce
Steps to reproduce the behavior: Just go into any stages and find a star

Expected behavior
They're supposed to be yellow.

Device:
 - FW: 11.13.0-45E
 - Daedalus Version [e.g. 0.1]

Additional context

**Comment by L-i-n-u-x-C-a-t** [comment]
If anyone sees this, has it been corrected in 0.2 ? Same things happen to me but not on the right of the screen (see images)
![2030-05-06_10-54-07 611_top](https://user-images.githubusercontent.com/46047705/81277666-05ac0180-9055-11ea-85ba-6f2155a7bf2d.png)
![2030-05-06_10-56-08 018_top](https://user-images.githubusercontent.com/46047705/81277671-06dd2e80-9055-11ea-9082-36fad60c2d38.png)

**Comment by MisterPrintf** [comment]
I can confirm this bug is still present as of the 0.2 release.

**Comment by Deadfalt999** [comment]
Fixed as of the 0.3 release, same for the hazy maze cave portal and metal mario.
